import { Navigation } from "~/components/shared";
import type { Metadata } from "next";
import { inter } from "~/app/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Todo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased w-full h-full bg-neutral-950`}
      >
        <Navigation />
        <main className="min-h-screen flex flex-col items-center justify-center py-32">
          {children}
        </main>
      </body>
    </html>
  );
}
